---
- name: Check for compliance of rules
  include_tasks: "{{ windows_2016_uat_item }}"
  loop:
    - rules/secedit.yml
    - rules/localpolicies.yml
    - rules/windowsfirewall.yml
    - rules/advancedauditpolicyconfiguration.yml
#    - rules/lgpo.yml
    - rules/administrativetemplatescomputer.yml
  loop_control:
    loop_var: windows_2016_uat_item
