---
- name: 1.1.1 (L1) Ensure 'Enforce password history' is set to '24 or more password(s)'
  win_security_policy:
    section: System Access
    key: PasswordHistorySize
    value: 24
- name: 1.1.2 (L1) Ensure 'Maximum password age' is set to '60 or fewer days, but not 0'
  win_security_policy:
    section: System Access
    key: MaximumPasswordAge 
    value: 60        
- name: 1.1.3 (L1) Ensure 'Minimum password age' is set to '1 or more day(s)'
  win_security_policy:
    section: System Access
    key: MinimumPasswordAge 
    value: 1 
- name: 1.1.4 (L1) Ensure 'Minimum password length' is set to '14 or more character(s)'
  win_security_policy:
    section: System Access
    key: MinimumPasswordLength  
    value: 14
- name: 1.1.5 (L1) Ensure 'Password must meet complexity requirements' is set to 'Enabled'
  win_security_policy:
    section: System Access
    key: PasswordComplexity  
    value: 1
- name: 1.1.6 (L1) Ensure 'Store passwords using reversible encryption' is set to 'Disabled'
  win_security_policy:
    section: System Access
    key: ClearTextPassword  
    value: 0
- name: 1.2.2 (L1) Ensure 'Account lockout threshold' is set to '10 or fewer invalid logon attempt(s), but not 0'
  win_security_policy:
    section: System Access
    key: LockoutBadCount  
    value: 10                                                                           
- name: 1.2.3 (L1) Ensure 'Reset account lockout counter after' is set to '15 or more minute(s)'
  win_security_policy:
    section: System Access
    key: ResetLockoutCount
    value: 15
- name: 1.2.1 (L1) Ensure 'Account lockout duration' is set to '15 or more minute(s)'
  win_security_policy:
    section: System Access
    key: LockoutDuration
    value: 15
- name: 2.2.1 (L1) Ensure 'Access Credential Manager as a trusted caller' is set to 'No One'
  win_security_policy:
    section: Privilege Rights
    key: SeTrustedCredManAccessPrivilege
    value: ""
- name: 2.2.2 (L1) Configure 'Access this computer from the network'
  win_security_policy:
    section: Privilege Rights
    key: SeNetworkLogonRight
    value: "*S-1-1-0,*S-1-5-32-544,*S-1-5-32-545,*S-1-5-32-551"
- name: 2.2.5 (L1) Ensure 'Adjust memory quotas for a process' is set to 'Administrators, LOCAL SERVICE, NETWORK SERVICE'
  win_security_policy:
    section: Privilege Rights
    key: SeTcbPrivilege
    value: ""    
- name: 2.2.6 (L1) Ensure 'Allow log on locally' is set to 'Administrators'
  win_security_policy:
    section: Privilege Rights
    key: SeInteractiveLogonRight
    value: "*S-1-5-32-544"                